### ISSUE TITLE
meta: Project Plan

### ISSUE THREAD

**Issue by mewmew** [decomp/decomp#1]
# Project Plan
- [x] Issue #17 - Introduction
- [x] Issue #22 - Literature Review
- [x] Issue #35 - Related Work
- [x] Issue #49 - Methodology
- [x] Issue #48 - Requirements (MUST)
- [x] Issue #55 - Design (MUST)
- [x] Issue #60 - Implementation (MUST)
- [x] Issue #116 - Verification
- [x] Issue #64 - Evaluation (MUST)
- [x] Issue #69 - Conclusion

**Comment by mewmew** [comment]
The project report is now finished, and has been made available online ([decompilation.pdf](https://raw.githubusercontent.com/mewpaper/decompilation/master/decompilation.pdf)). It was submitted for printing on the 22nd of April at 16:09, 2015.
