### ISSUE TITLE
meta: Time estimates

### ISSUE THREAD

**Issue by mewmew** [decomp/decomp#149]
# Completed tasks
## Small tasks
- [x] [Benchmarks](https://github.com/mewpaper/decompilation/issues/67)
- [x] [Build Status (CI)](https://github.com/mewpaper/decompilation/issues/140)
- [x] [Code Correctness (CI)](https://github.com/mewpaper/decompilation/issues/139)
- [x] [Code Coverage (CI)](https://github.com/mewpaper/decompilation/issues/142)
- [x] [Code Coverage](https://github.com/mewpaper/decompilation/issues/135)
- [x] [Coding Style (CI)](https://github.com/mewpaper/decompilation/issues/138)
- [x] [Compilers](https://github.com/mewpaper/decompilation/issues/129)
- [x] [Conclusion](https://github.com/mewpaper/decompilation/issues/69)
- [x] [Continuous Integration](https://github.com/mewpaper/decompilation/issues/120)
- [x] [Evaluation of Intermediate Representations](https://github.com/mewpaper/decompilation/issues/23)
- [x] [Evaluation](https://github.com/mewpaper/decompilation/issues/64)
- [x] [Final Thoughts](https://github.com/mewpaper/decompilation/issues/73)
- [x] [Generate final Gantt chart](https://github.com/mewpaper/decompilation/issues/85)
- [x] [Hex-Rays Decompiler](https://github.com/mewpaper/decompilation/issues/45)
- [x] [Language Considerations](https://github.com/mewpaper/decompilation/issues/143)
- [x] [Literature Review](https://github.com/mewpaper/decompilation/issues/22)
- [x] [Native Code to LLVM IR](https://github.com/mewpaper/decompilation/issues/128)
- [x] [Native Code to LLVM IR](https://github.com/mewpaper/decompilation/issues/36)
- [x] [Performance](https://github.com/mewpaper/decompilation/issues/118)
- [x] [Profiling](https://github.com/mewpaper/decompilation/issues/136)
- [x] [REIL](https://github.com/mewpaper/decompilation/issues/25)
- [x] [Related Work](https://github.com/mewpaper/decompilation/issues/35)
- [x] [Test Cases (CI)](https://github.com/mewpaper/decompilation/issues/141)
- [x] [Test Cases](https://github.com/mewpaper/decompilation/issues/134)
- [x] [Verification](https://github.com/mewpaper/decompilation/issues/116)
## Medium tasks
- [x] [Dagger](https://github.com/mewpaper/decompilation/issues/46)
- [x] [Evolutionary Prototyping](https://github.com/mewpaper/decompilation/issues/124)
- [x] [Go Bindings for LLVM](https://github.com/mewpaper/decompilation/issues/152)
- [x] [LLVM IR](https://github.com/mewpaper/decompilation/issues/26)
- [x] [MC-Semantics](https://github.com/mewpaper/decompilation/issues/90)
- [x] [Methodology](https://github.com/mewpaper/decompilation/issues/49)
- [x] [Operational Prototyping](https://github.com/mewpaper/decompilation/issues/125)
- [x] [Security Assessment](https://github.com/mewpaper/decompilation/issues/119)
- [x] [Throwaway Prototyping](https://github.com/mewpaper/decompilation/issues/50)
- [x] [Throwaway Prototyping](https://github.com/mewpaper/decompilation/issues/50)
## Large tasks
- [x] [Back-end Components](https://github.com/mewpaper/decompilation/issues/56)
- [x] [Control Flow Analysis Library](https://github.com/mewpaper/decompilation/issues/154)
- [x] [Control Flow Analysis Tool](https://github.com/mewpaper/decompilation/issues/155)
- [x] [Control Flow Analysis](https://github.com/mewpaper/decompilation/issues/131)
- [x] [Control Flow Analysis](https://github.com/mewpaper/decompilation/issues/34)
- [x] [Control Flow Graph Generation](https://github.com/mewpaper/decompilation/issues/130)
- [x] [Design](https://github.com/mewpaper/decompilation/issues/55)
- [x] [Disassembly](https://github.com/mewpaper/decompilation/issues/29)
- [x] [Front-end Components](https://github.com/mewpaper/decompilation/issues/58)
- [x] [Future Work](https://github.com/mewpaper/decompilation/issues/68)
- [x] [LLVM IR Library](https://github.com/mewpaper/decompilation/issues/144)
- [x] [LLVM IR Library](https://github.com/mewpaper/decompilation/issues/153)
- [x] [Middle-end Components](https://github.com/mewpaper/decompilation/issues/57)
- [x] [Post-processing](https://github.com/mewpaper/decompilation/issues/133)
- [x] [Project Summary](https://github.com/mewpaper/decompilation/issues/70)
- [x] [Subgraph Isomorphism Search Library](https://github.com/mewpaper/decompilation/issues/146)
- [x] [System Architecture](https://github.com/mewpaper/decompilation/issues/59)

**Comment by mewmew** [comment]
Three weeks, wow.
