### ISSUE TITLE
meta: Reorganization of repositories

### ISSUE THREAD

**Issue by mewmew** [decomp/decomp#174]
Following the same rationale as the one discussed in azul3d/engine#1, the repositories of `decomp` will be combined into a single repository, namely this one. The primary reason is to facilitate development, help users track progress, and make it easier to track issues and manage stable versions.

Note that the decompilation pipeline will still be composed of independent components interacting through well-defined interfaces, as has always been the case. The only change is that the code of these components will be contained in a single repository, and issues related to their development will be tracked by a single issue tracker.

Planed restructuring:
- [x] Move LaTeX files related to the project report into a dedicated `report` directory. Now part of the `decomp/doc` repo.
- [x] Move `decomp/ll2dot` to `decomp/decomp/cmd/ll2dot`
- [x] Move `decomp/restructure` to `decomp/decomp/cmd/restructure`
- [x] Move `decomp/ll2go` to `decomp/decomp/cmd/ll2go`
- [x] Move `decomp/go-post` to `decomp/decomp/cmd/post`
- [x] Move `decomp/graphs` to `decomp/decomp/graphs`
- [x] Move `decomp/exp` to `decomp/decomp/exp`? No, keep it as a dedicated repository for throw-away prototypes.
- [x] Fix links in `README`s
- [x] Simplify imports (get rid of vanity imports); e.g. import `github.com/decomp/decomp/foo` rather than `decomp.org/decomp/foo`.

As part of this reorganization, the git repo will be cleaned to reduce its size. Large files will be tracked using [LFS](https://git-lfs.github.com/).

**Comment by mewmew** [comment]
Images and PDFs added using LFS in commit bc20c9793f63138e9e5164a78ffdb415c4373bc5.

To shrink the repository size, the instructions outlined in http://stevelorek.com/how-to-shrink-a-git-repository.html were followed.

**Comment by mewmew** [comment]
Even with LFS tracking of images and PDFs, the size of the repository is still quite large; 27.7 M in total (out of which the `.git` directory takes 14.2 M). For this reason, the documentation will be pulled out from the [decomp/decomp](https://github.com/decomp/decomp) repository and placed in a dedicated [decomp/doc](https://github.com/decomp/doc) repo. The [decomp/decomp](https://github.com/decomp/decomp) repository will contain the source code of the decompilation components, and to facilitate development the repository size will be kept smaller, so that `go get` should be possible within seconds rather than minutes on slow connections.

**Comment by mewmew** [comment]
The primary re-organization for v0.2 has now been completed.
