### ISSUE TITLE
meta: Literature review

### ISSUE THREAD

**Issue by mewmew** [decomp/decomp#2]
The following theses, papers, and online references will be included in the literature review:
- [ ] Issue #76 - C. Cifuentes, _Reverse Compilation Techniques_. PhD thesis, Queensland University of Technology, 1994.
- [x] Issue #80 - I. Guilfanov, _Decompilers and beyond_. Black Hat USA, 2008.
- [x] Issue #16: S. Moll, _Decompilation of LLVM IR_. BSc thesis, Saarland University, 2011.
- [x] Issue #81 - L. Ďurfina, J. Křoustek, P. Zemek, D. Kolář, T. Hruška, K. Masařík, and A. Meduna, _Design of a retargetable decompiler for a static platform-independent malware analysis_, in Information Security and Assurance (pp. 72-86), Springer, 2011.
- [x] Issue #82 - G. Chen, Z. Qi, S. Huang, K. Ni, Y. Zheng, W. Binder, and H. Guan, _A refined decompiler to generate C code with high readability_, Software: Practice and Experience, vol. 43, no. 11, pp. 1337-1358, 2013.
- [ ] Issue #83 - K. Yakdan, S. Eschweiler, and E. Gerhards-Padilla, _REcompile: A Decompilation Framework for Static Analysis of Binaries_, in MALWARE'13, pp. 95-102, IEEE, 2013.
- [ ] Issue #75 - [LLVM Language Reference Manual](http://llvm.org/docs/LangRef.html).
- [x] Issue #13 - [LLVM Bitcode File Format](http://llvm.org/docs/BitCodeFormat.html).

The following theses, papers, and online references have been marked as future ambitions:
- Issue #77 - A. Mycroft, _Type-Based Decompilation_, in 8th European Symposium on Programming, ESOP'99, pp. 208–223, Springer-Verlag, 1999.
- Issue #78 - M. J. Van Emmerik, _Static Single Assignment for Decompilation_. PhD thesis, The University of Queensland, 2007.
- Issue #79 - T. Durden, _Automated vulnerability auditing in machine code_, Phrack Magazine, vol. 64, 2007.

**Comment by mewmew** [comment]
The majority of the literature have been conducted, and the remaining papers have individually been marked as future ambitions. Closing for now.

**Comment by mewmew** [comment]
This issue has been superseded by #127.
