### ISSUE TITLE
meta: Report, A Meta-study on Type Analysis of Low-level Code

### ISSUE THREAD

**Issue by mewmew** [decomp/decomp#215]
This is a *draft* of the [report](https://github.com/decomp/doc/tree/master/report/type_analysis) structure.

1. [x] Introduction
	1. [x] Problem definition
	2. [x] Aim
	3. [x] Scope
2. [ ] Background
	1. [ ] Static Single Assignment
	2. [ ] Type Lattice
	3. [ ] Static Analysis
	4. [ ] Dynamic Analysis
3. [x] Variable Recovery
	1. [ ] Value Set Analysis
	2. [ ] Function signature recovery
4. [ ] Type Recovery
	1. [ ] Type inferrence
		1. [ ] Value-based inference
		2. [ ] Flow-based inference
		3. [ ] Instruction type sources
		4.  [ ] Function type sources
		5. [ ] Type sink
	3. [ ] Type propagation
	4. [ ] Unification
	5. [ ] Pointer analysis
5. [x] Evaluation Metrics
	1. [x] Distance
	2. [x] Conservativeness
6. [ ] Discussion
	1. [ ] Future Applications
	2. [ ] Future Research
