### ISSUE TITLE
report: Literature Review [2h]

### ISSUE THREAD

**Issue by mewmew** [decomp/decomp#22]
- [x] Issue #87 - The Anatomy of an Executable
- [x] Issue #28 - Decompilation Phases
  - [x] Issue #86 - Binary Analysis
  - [x] Issue #29 - Disassembly
  - [x] Issue #34 - Control Flow Analysis
- [x] Issue #23 - Evaluation of Intermediate Representations
  - [x] Issue #25 - REIL
  - [x] Issue #26 - LLVM IR

**Comment by pfalcon** [comment]
Ye greate dump of stuff: https://github.com/REMath/literature_review

**Comment by mewmew** [comment]
@pfalcon I know the [REMath reddit community](https://www.reddit.com/r/REMath/) have a lot of great resources.

I copied your link to the issue #127 (which has superseded this issue) to track research notes.

**Comment by pfalcon** [comment]
> REMath reddit community 

Thanks, never heard about it.
