### ISSUE TITLE
meta: Report, Compositional Decompilation using LLVM IR

### ISSUE THREAD

**Issue by mewmew** [decomp/decomp#3]
- [x] Issue #115 - Abstract
- [x] Issue #17 - Introduction
  - [x] Issue #19 - Project Aim and Objectives
  - [x] Issue #20 - Deliverables
  - [x] Issue #21 - Disposition
- [x] Issue #22 - Literature Review
  - [x] Issue #87 - The Anatomy of an Executable
  - [x] Issue #28 - Decompilation Phases
    - [x] Issue #86 - Binary Analysis
    - [x] Issue #29 - Disassembly
    - [x] Issue #34 - Control Flow Analysis
  - [x] Issue #23 - Evaluation of Intermediate Representations
    - [x] Issue #25 - REIL
    - [x] Issue #26 - LLVM IR
- [x] Issue #35 - Related Work
  - [x] Issue #36 - Native Code to LLVM IR
    - [x] Issue #46 - Dagger
    - [x] Issue #90 - MC-Semantics
  - [x] Issue #45 - Hex-Rays Decompiler
- [x] Issue #49 - Methodology
  - [x] Issue #125 - Operational Prototyping
    - [x] Issue #50 - Throwaway Prototyping
    - [x] Issue #124 - Evolutionary Prototyping
  - [x] Issue #53 - Continuous Integration
- [x] Issue #48 - Requirements
  - [x] Issue #121 - LLVM IR Library
  - [x] Issue #122 - Control Flow Analysis Library
  - [x] Issue #123 - Control Flow Analysis Tool
- [x] Issue #55 - Design
  - [x] Issue #59 - System Architecture
  - [x] Issue #58 - Front-end Components
    - [x] Issue #128 - Native Code to LLVM IR
    - [x] Issue #129 - Compilers
  - [x] Issue #57 - Middle-end Components
    - [x] Issue #130 - Control Flow Graph Generation
    - [x] Issue #131 - Control Flow Analysis
  - [x] Issue #56 - Back-end Components
    - [x] Issue #133 - Post-processing
- [x] Issue #60 - Implementation
  - [x] Issue #143 - Language Considerations
  - [x] Issue #144 - LLVM IR Library
  - [x] Issue #152 - Go Bindings for LLVM
  - [x] Issue #146 - Subgraph Isomorphism Search Library
  - [x] Issue #61 - Documentation
- [x] Issue #116 - Verification
  - [x] Issue #134 - Test Cases
    - [x] Issue #135 - Code Coverage
  - [x] Issue #118 - Performance
    - [x] Issue #136 - Profiling
    - [x] Issue #67 - Benchmarks
  - [x] Issue #119 - Security Assessment
  - [x] Issue #120 - Continuous Integration
    - [x] Issue #137 - Source Code Formatting
    - [x] Issue #138 - Coding Style
    - [x] Issue #139 - Code Correctness
    - [x] Issue #140 - Build Status
    - [x] Issue #141 - Test Cases
    - [x] Issue #142 - Code Coverage
- [x] Issue #64 - Evaluation
  - [x] Issue #153 - LLVM IR Library
    - [x] Issue #159 - Essential Requirements
    - [x] Issue #160 - Desirable Requirements
  - [x] Issue #154 - Control Flow Analysis Library
    - [x] Issue #161 - Essential Requirements
    - [x] Issue #162 - Important Requirements
    - [x] Issue #163 - Desirable Requirements
  - [x] Issue #155 - Control Flow Analysis Tool
    - [x] Issue #164 - Essential Requirements
- [x] Issue #69 - Conclusion
  - [x] Issue #70 - Project Summary
  - [x] Issue #68 - Future Work
    - [x] Issue #156 - Design Validation
    - [x] Issue #157 - Reliability Improvements
    - [x] Issue #158 - Extended Capabilities
  - [x] Issue #72 - Personal Development
  - [x] Issue #73 - Final Thoughts

**Comment by mewmew** [comment]
Once finished, the report included 75 sections and subsections, not including the abstract and the appendices.
