### ISSUE TITLE
report: Related Work [3h]

### ISSUE THREAD

**Issue by mewmew** [decomp/decomp#35]
- [x] Issue #36 - Native Code to LLVM IR
  - [x] Issue #46 - Dagger
  - [x] Issue #90 - MC-Semantics
- [x] Issue #45 - Hex-Rays Decompiler
