### ISSUE TITLE
report: Requirements [6h]

### ISSUE THREAD

**Issue by mewmew** [decomp/decomp#48]
- [x] Issue #121 - LLVM IR Library
- [x] Issue #122 - Structural Analysis Library
- [x] Issue #123 - Structural Analysis Tool

**Comment by mewmew** [comment]
Actual time spent: 18h. This includes researching MoSCoW and reading other dissertations.
