### ISSUE TITLE
report: Methodology [1h]

### ISSUE THREAD

**Issue by mewmew** [decomp/decomp#49]
- [x] Issue #125 - Operational Prototyping
  - [x] Issue #50 - Throwaway Prototyping
  - [x] Issue #124 - Evolutionary Prototyping
- [x] Issue #53 - Continuous Integration
