### ISSUE TITLE
report: Design [6h]

### ISSUE THREAD

**Issue by mewmew** [decomp/decomp#55]
- [x] Issue #59 - System Architecture
- [x] Issue #58 - Front-end Components
  - [x] Issue #128 - Native Code to LLVM IR
  - [x] Issue #129 - Compilers
- [x] Issue #57 - Middle-end Components
  - [x] Issue #130 - Control Flow Graph Generation
  - [x] Issue #131 - Control Flow Analysis
- [x] Issue #56 - Back-end Components
  - [x] Issue #133 - Post-processing
