### ISSUE TITLE
report: Implementation [3h]

### ISSUE THREAD

**Issue by mewmew** [decomp/decomp#60]
- [x] Issue #143 - Language Considerations
- [x] Issue #144 - LLVM IR Library
- [x] Issue #152 - Go Bindings for LLVM
- [x] Issue #146 - Subgraph Isomorphism Search Library
- [x] Issue #61 - Documentation
