### ISSUE TITLE
report: Evaluation [10h]

### ISSUE THREAD

**Issue by mewmew** [decomp/decomp#64]
- [x] Issue #153 - LLVM IR Library
  - [x] Issue #159 - Essential Requirements
  - [x] Issue #160 - Desirable Requirements
- [x] Issue #154 - Control Flow Analysis Library
  - [x] Issue #161 - Essential Requirements
  - [x] Issue #162 - Important Requirements
  - [x] Issue #163 - Desirable Requirements
- [x] Issue #155 - Control Flow Analysis Tool
  - [x] Issue #164 - Essential Requirements
